apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: capstone-app

resources:
  - deployment.yaml

commonLabels:
  app.kubernetes.io/part-of: capstone
  app.kubernetes.io/managed-by: kustomize

images:
  - name: capstone-api
    newName: 000000000000.dkr.ecr.us-east-1.amazonaws.com/gha-terraform-eks-dev-capstone-api
    newTag: latest
