server {
    listen 80;
    server_name _;

    location / {
        root /usr/share/nginx/html;
        index index.html;
    }

    location /health {
        default_type application/json;
        alias /usr/share/nginx/html/health/index.json;
        access_log off;
    }
}
