apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namePrefix: dev-

patches:
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
      - op: replace
        path: /spec/template/spec/containers/0/env/0/value
        value: dev
    target:
      kind: Deployment
      name: capstone-api

images:
  - name: capstone-api
    newName: 000000000000.dkr.ecr.us-east-1.amazonaws.com/gha-terraform-eks-dev-capstone-api
    newTag: latest
